/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __TEST_EXT_ICE_H__
#define __TEST_EXT_ICE_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <test/test_cpp_ext.h>

///////////////////////////////////////////////////////////////////////////////

class TestExtIce : public TestCppExt {
 public:
  virtual bool RunTests(const std::string &which);

  bool test_ice_initialize();
  bool test_icephp_defineproxy();
  bool test_icephp_declareclass();
  bool test_icephp_defineexception();
  bool test_create_typeinfobyid();
  bool test_icephp_stringifyexception();
  bool test_icephp_stringify();
  bool test_icephp_definesequence();
  bool test_icephp_defineclass();
  bool test_icephp_defineoperation();
  bool test_ice_find();
  bool test_ice_register();
  bool test_ICE();
  bool test_Proxy();
  bool test_IcePHP_class();
  bool test_TypeInfo();
};

///////////////////////////////////////////////////////////////////////////////

#endif // __TEST_EXT_ICE_H__
