/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXTPROFILE_HHVM_SF_H__
#define __EXTPROFILE_HHVM_SF_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_hhvm_sf.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline void x_is_hhvm_func() {
  FUNCTION_INJECTION_BUILTIN(is_hhvm_func);
  f_is_hhvm_func();
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_HHVM_SF_H__
