/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_MSSQL_H__
#define __EXT_MSSQL_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

Variant f_mssql_connect(CStrRef server = null_string, CStrRef username = null_string, CStrRef password = null_string, bool new_link = false);
Variant f_mssql_pconnect(CStrRef server = null_string, CStrRef username = null_string, CStrRef password = null_string, bool new_link = false);
bool f_mssql_close(CVarRef link_identifier = null);
bool f_mssql_select_db(CStrRef database_name = null, CVarRef link_identifier = null);
Variant f_mssql_query(CStrRef query = null, CVarRef link_identifier = null, int64 batch_size = 0);
Variant f_mssql_num_rows(CVarRef result = null);
Variant f_mssql_rows_affected(CVarRef result = null);
Variant f_mssql_fetch_row(CVarRef result = null);
Variant f_mssql_fetch_assoc(CVarRef result = null);
Variant f_mssql_free_result(CVarRef result = null);
Variant f_mssql_get_last_message();

///////////////////////////////////////////////////////////////////////////////
// class MssqlResult

FORWARD_DECLARE_CLASS_BUILTIN(MssqlResult);
class c_MssqlResult : public ExtObjectData {
 public:
  DECLARE_CLASS(MssqlResult, MssqlResult, ObjectData)

  // need to implement
  public: c_MssqlResult(const ObjectStaticCallbacks *cb = &cw_MssqlResult);
  public: ~c_MssqlResult();
  public: void t___construct();
  DECLARE_METHOD_INVOKE_HELPERS(__construct);
  public: String t___tostring();
  DECLARE_METHOD_INVOKE_HELPERS(__tostring);

  // implemented by HPHP
  public: c_MssqlResult *create();

};

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_MSSQL_H__
