/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __TEST_EXT_MSSQL_H__
#define __TEST_EXT_MSSQL_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <test/test_cpp_ext.h>

///////////////////////////////////////////////////////////////////////////////

class TestExtMssql : public TestCppExt {
 public:
  virtual bool RunTests(const std::string &which);

  bool test_mssql_connect();
  bool test_mssql_pconnect();
  bool test_mssql_close();
  bool test_mssql_select_db();
  bool test_mssql_query();
  bool test_mssql_num_rows();
  bool test_mssql_rows_affected();
  bool test_mssql_fetch_row();
  bool test_mssql_fetch_assoc();
  bool test_mssql_free_result();
  bool test_mssql_get_last_message();
  bool test_MssqlResult();
};

///////////////////////////////////////////////////////////////////////////////

#endif // __TEST_EXT_MSSQL_H__
